from boto3 import Session
from botocore.exceptions import BotoCoreError, ClientError
import os
import time
from contextlib import closing

entries = {
  "Äitilimanuljaska": '<speak><prosody rate="60%"><w role="amazon:NN">Äitilimanuljaska</w></prosody></speak>',
  "Äitinuljaska": '<speak><prosody rate="60%"><w role="amazon:NN">Äitinuljaska</w></prosody></speak>',
  "Alkemisti": '<speak><prosody rate="60%"><w role="amazon:NN">Alkemisti</w></prosody></speak>',
  "Alkemistin Varjo": '<speak><prosody rate="60%"><w role="amazon:NN">Alkemistin Varjo</w></prosody></speak>',
  "Amppari": '<speak><prosody rate="60%"><w role="amazon:NN">Amppari</w></prosody></speak>',
  "Ankka": '<speak><prosody rate="60%"><w role="amazon:NN">Ankka</w></prosody></speak>',
  "Arpaluu": '<speak><prosody rate="60%"><w role="amazon:NN">Arpaluu</w></prosody></speak>',
  "Auringonmuna": '<speak><prosody rate="60%"><w role="amazon:NN">Auringonmuna</w></prosody></speak>',
  "Auringonsiemen": '<speak><prosody rate="60%"><w role="amazon:NN">Auringonsiemen</w></prosody></speak>',
  "Aurinkokivi": '<speak><prosody rate="60%"><w role="amazon:NN">Aurinkokivi</w></prosody></speak>',
  "Eldari": '<speak><prosody rate="60%"><w role="amazon:NN">Eldari</w></prosody></speak>',
  "Elvytyskristalli": '<speak><prosody rate="60%"><w role="amazon:NN">Elvytyskristalli</w></prosody></speak>',
  "Epäalkemisti": '<speak><prosody rate="60%"><w role="amazon:NN">Epäalkemisti</w></prosody></speak>',
  "Eväkäs": '<speak><prosody rate="60%"><w role="amazon:NN">Eväkäs</w></prosody></speak>',
  "Haamu": '<speak><prosody rate="60%"><w role="amazon:NN">Haamu</w></prosody></speak>',
  "Haamukivi": '<speak><prosody rate="60%"><w role="amazon:NN">Haamukivi</w></prosody></speak>',
  "Haavoittajamestari": '<speak><prosody rate="60%"><w role="amazon:NN">Haavoittajamestari</w></prosody></speak>',
  "Hahmonvaihtaja": '<speak><prosody rate="60%"><w role="amazon:NN">Hahmonvaihtaja</w></prosody></speak>',
  "Häive": '<speak><prosody rate="60%"><w role="amazon:NN">Häive</w></prosody></speak>',
  "Häivehiisi": '<speak><prosody rate="60%"><w role="amazon:NN">Häivehiisi</w></prosody></speak>',
  "Hämähäkki": '<speak><prosody rate="60%"><w role="amazon:NN">Hämähäkki</w></prosody></speak>',
  "Hämis": '<speak><prosody rate="60%"><w role="amazon:NN">Hämis</w></prosody></speak>',
  "Happonuljaska": '<speak><prosody rate="60%"><w role="amazon:NN">Happonuljaska</w></prosody></speak>',
  "Haulikkohiisi": '<speak><prosody rate="60%"><w role="amazon:NN">Haulikkohiisi</w></prosody></speak>',
  "Heikko äitinuljaska": '<speak><prosody rate="60%"><w role="amazon:NN">Heikko äitinuljaska</w></prosody></speak>',
  "Heikko happonuljaska": '<speak><prosody rate="60%"><w role="amazon:NN">Heikko happonuljaska</w></prosody></speak>',
  "Heikko haulikkohiisi": '<speak><prosody rate="60%"><w role="amazon:NN">Heikko haulikkohiisi</w></prosody></speak>',
  "Heikko limanuljaska": '<speak><prosody rate="60%"><w role="amazon:NN">Heikko limanuljaska</w></prosody></speak>',
  "Heikkohurtta": '<speak><prosody rate="60%"><w role="amazon:NN">Heikkohurtta</w></prosody></speak>',
  "Heinäsirkka": '<speak><prosody rate="60%"><w role="amazon:NN">Heinäsirkka</w></prosody></speak>',
  "Helvetin sylkijä": '<speak><prosody rate="60%"><w role="amazon:NN">Helvetin sylkijä</w></prosody></speak>',
  "Helvetinkatse": '<speak><prosody rate="60%"><w role="amazon:NN">Helvetinkatse</w></prosody></speak>',
  "Helvetinmato": '<speak><prosody rate="60%"><w role="amazon:NN">Helvetinmato</w></prosody></speak>',
  "Hernekeittopurkki": '<speak><prosody rate="60%"><w role="amazon:NN">Hernekeittopurkki</w></prosody></speak>',
  "Hiidenkivi": '<speak><prosody rate="60%"><w role="amazon:NN">Hiidenkivi</w></prosody></speak>',
  "Hohtava hyypiö": '<speak><prosody rate="60%"><w role="amazon:NN">Hohtava hyypiö</w></prosody></speak>',
  "Hohtonaamio": '<speak><prosody rate="60%"><w role="amazon:NN">Hohtonaamio</w></prosody></speak>',
  "Houre": '<speak><prosody rate="60%"><w role="amazon:NN">Houre</w></prosody></speak>',
  "Huhtasieni": '<speak><prosody rate="60%"><w role="amazon:NN">Huhtasieni</w></prosody></speak>',
  "Huilu": '<speak><prosody rate="60%"><w role="amazon:NN">Huilu</w></prosody></speak>',
  "Hurtta": '<speak><prosody rate="60%"><w role="amazon:NN">Hurtta</w></prosody></speak>',
  "Hyypiö": '<speak><prosody rate="60%"><w role="amazon:NN">Hyypiö</w></prosody></speak>',
  "Isohiisi": '<speak><prosody rate="60%"><w role="amazon:NN">Isohiisi</w></prosody></speak>',
  "IT-Tankki": '<speak><prosody rate="60%"><w role="amazon:NN"><say-as interpret-as="spell-out">IT</say-as>-Tankki</w></prosody></speak>',
  "Itiösieni": '<speak><prosody rate="60%"><w role="amazon:NN">Itiösieni</w></prosody></speak>',
  "Jäähdytyslaite": '<speak><prosody rate="60%"><w role="amazon:NN">Jäähdytyslaite</w></prosody></speak>',
  "Jäätiö": '<speak><prosody rate="60%"><w role="amazon:NN">Jäätiö</w></prosody></speak>',
  "Jalkamatkatavara": '<speak><prosody rate="60%"><w role="amazon:NN">Jalkamatkatavara</w></prosody></speak>',
  "Jättikonna": '<speak><prosody rate="60%"><w role="amazon:NN">Jättikonna</w></prosody></speak>',
  "Jättilaser-lennokki": '<speak><prosody rate="60%"><w role="amazon:NN">Jättilaser-lennokki</w></prosody></speak>',
  "Jättimato": '<speak><prosody rate="60%"><w role="amazon:NN">Jättimato</w></prosody></speak>',
  "Jouluhiisi": '<speak><prosody rate="60%"><w role="amazon:NN">Jouluhiisi</w></prosody></speak>',
  "Juhannussima": '<speak><prosody rate="60%"><w role="amazon:NN">Juhannussima</w></prosody></speak>',
  "Kadotettu alkemisti": '<speak><prosody rate="60%"><w role="amazon:NN">Kadotettu alkemisti</w></prosody></speak>',
  "Kakkakikkare": '<speak><prosody rate="60%"><w role="amazon:NN">Kakkakikkare</w></prosody></speak>',
  "Kaljapullo": '<speak><prosody rate="60%"><w role="amazon:NN">Kaljapullo</w></prosody></speak>',
  "Kallokärpänen": '<speak><prosody rate="60%"><w role="amazon:NN">Kallokärpänen</w></prosody></speak>',
  "Kallorotta": '<speak><prosody rate="60%"><w role="amazon:NN">Kallorotta</w></prosody></speak>',
  "Kalmamato": '<speak><prosody rate="60%"><w role="amazon:NN">Kalmamato</w></prosody></speak>',
  "Kammi": '<speak><prosody rate="60%"><w role="amazon:NN">Kammi</w></prosody></speak>',
  "Kammolukki": '<speak><prosody rate="60%"><w role="amazon:NN">Kammolukki</w></prosody></speak>',
  "Kantele": '<speak><prosody rate="60%"><w role="amazon:NN">Kantele</w></prosody></speak>',
  "Kärpässieni": '<speak><prosody rate="60%"><w role="amazon:NN">Kärpässieni</w></prosody></speak>',
  "Kasvoton Hämähäkki": '<speak><prosody rate="60%"><w role="amazon:NN">Kasvoton Hämähäkki</w></prosody></speak>',
  "Kasvoton Lukki": '<speak><prosody rate="60%"><w role="amazon:NN">Kasvoton Lukki</w></prosody></speak>',
  "Kauhuhirviö": '<speak><prosody rate="60%"><w role="amazon:NN">Kauhuhirviö</w></prosody></speak>',
  "Kiekurakeppi": '<speak><prosody rate="60%"><w role="amazon:NN">Kiekurakeppi</w></prosody></speak>',
  "Kilpihiisi": '<speak><prosody rate="60%"><w role="amazon:NN">Kilpihiisi</w></prosody></speak>',
  "Kirottu kristalli": '<speak><prosody rate="60%"><w role="amazon:NN">Kirottu kristalli</w></prosody></speak>',
  "Kiuaskivi": '<speak><prosody rate="60%"><w role="amazon:NN">Kiuaskivi</w></prosody></speak>',
  "Kiukkukalma": '<speak><prosody rate="60%"><w role="amazon:NN">Kiukkukalma</w></prosody></speak>',
  "Kiukkumöykky": '<speak><prosody rate="60%"><w role="amazon:NN">Kiukkumöykky</w></prosody></speak>',
  "KK-Tankki": '<speak><prosody rate="60%"><w role="amazon:NN"><say-as interpret-as="spell-out">KK</say-as>-Tankki</w></prosody></speak>',
  "Kohdennusmestari": '<speak><prosody rate="60%"><w role="amazon:NN">Kohdennusmestari</w></prosody></speak>',
  "Kokkihiisi": '<speak><prosody rate="60%"><w role="amazon:NN">Kokkihiisi</w></prosody></speak>',
  "Kolmisilmä": '<speak><prosody rate="60%"><w role="amazon:NN">Kolmisilmä</w></prosody></speak>',
  "Kolmisilmän apuri": '<speak><prosody rate="60%"><w role="amazon:NN">Kolmisilmän apuri</w></prosody></speak>',
  "Kolmisilmän kätyri": '<speak><prosody rate="60%"><w role="amazon:NN">Kolmisilmän kätyri</w></prosody></speak>',
  "Kolmisilmän koipi": '<speak><prosody rate="60%"><w role="amazon:NN">Kolmisilmän koipi</w></prosody></speak>',
  "Kolmisilmän silmä": '<speak><prosody rate="60%"><w role="amazon:NN">Kolmisilmän silmä</w></prosody></speak>',
  "Konna": '<speak><prosody rate="60%"><w role="amazon:NN">Konna</w></prosody></speak>',
  "Korjauslennokki": '<speak><prosody rate="60%"><w role="amazon:NN">Korjauslennokki</w></prosody></speak>',
  "Kranuhiisi": '<speak><prosody rate="60%"><w role="amazon:NN">Kranuhiisi</w></prosody></speak>',
  "Kuihduttajamestari": '<speak><prosody rate="60%"><w role="amazon:NN">Kuihduttajamestari</w></prosody></speak>',
  "Kummitus": '<speak><prosody rate="60%"><w role="amazon:NN">Kummitus</w></prosody></speak>',
  "Kuu": '<speak><prosody rate="60%"><w role="amazon:NN">Kuu</w></prosody></speak>',
  "Kuulokivi": '<speak><prosody rate="60%"><w role="amazon:NN">Kuulokivi</w></prosody></speak>',
  "Kyrmyniska": '<speak><prosody rate="60%"><w role="amazon:NN">Kyrmyniska</w></prosody></speak>',
  "Laahustussieni": '<speak><prosody rate="60%"><w role="amazon:NN">Laahustussieni</w></prosody></speak>',
  "Lammas": '<speak><prosody rate="60%"><w role="amazon:NN">Lammas</w></prosody></speak>',
  "Laser-tankki": '<speak><prosody rate="60%"><w role="amazon:NN">Laser-tankki</w></prosody></speak>',
  "Laserkanuuna": '<speak><prosody rate="60%"><w role="amazon:NN">Laserkanuuna</w></prosody></speak>',
  "Lennokki": '<speak><prosody rate="60%"><w role="amazon:NN">Lennokki</w></prosody></speak>',
  "Lentolammas": '<speak><prosody rate="60%"><w role="amazon:NN">Lentolammas</w></prosody></speak>',
  "Lepakko": '<speak><prosody rate="60%"><w role="amazon:NN">Lepakko</w></prosody></speak>',
  "Liekkari": '<speak><prosody rate="60%"><w role="amazon:NN">Liekkari</w></prosody></speak>',
  "Liekkiö": '<speak><prosody rate="60%"><w role="amazon:NN">Liekkiö</w></prosody></speak>',
  "Liimahiisi": '<speak><prosody rate="60%"><w role="amazon:NN">Liimahiisi</w></prosody></speak>',
  "Limanuljaska": '<speak><prosody rate="60%"><w role="amazon:NN">Limanuljaska</w></prosody></speak>',
  "Limatoukka": '<speak><prosody rate="60%"><w role="amazon:NN">Limatoukka</w></prosody></speak>',
  "Lohkare": '<speak><prosody rate="60%"><w role="amazon:NN">Lohkare</w></prosody></speak>',
  "Lukki": '<speak><prosody rate="60%"><w role="amazon:NN">Lukki</w></prosody></speak>',
  "Lukki lair": '<speak><prosody rate="60%"><w role="amazon:NN">Lukki</w> <lang xml:lang="en-US">lair</lang></prosody></speak>',
  "Lukki Minion": '<speak><prosody rate="60%"><w role="amazon:NN">Lukki</w> <lang xml:lang="en-US">Minion</lang></prosody></speak>',
  "Maadoittajamestari": '<speak><prosody rate="60%"><w role="amazon:NN">Maadoittajamestari</w></prosody></speak>',
  "Maamiina": '<speak><prosody rate="60%"><w role="amazon:NN">Maamiina</w></prosody></speak>',
  "Mämmi": '<speak><prosody rate="60%"><w role="amazon:NN">Mämmi</w></prosody></speak>',
  "Märkiäinen": '<speak><prosody rate="60%"><w role="amazon:NN">Märkiäinen</w></prosody></speak>',
  "Marraskone": '<speak><prosody rate="60%"><w role="amazon:NN">Marraskone</w></prosody></speak>',
  "Mätänevä kroppa": '<speak><prosody rate="60%"><w role="amazon:NN">Mätänevä kroppa</w></prosody></speak>',
  "Mätänevä pää": '<speak><prosody rate="60%"><w role="amazon:NN">Mätänevä pää</w></prosody></speak>',
  "Mätänevä ruumis": '<speak><prosody rate="60%"><w role="amazon:NN">Mätänevä ruumis</w></prosody></speak>',
  "Matkija": '<speak><prosody rate="60%"><w role="amazon:NN">Matkija</w></prosody></speak>',
  "Mato": '<speak><prosody rate="60%"><w role="amazon:NN">Mato</w></prosody></speak>',
  "Matosade": '<speak><prosody rate="60%"><w role="amazon:NN">Matosade</w></prosody></speak>',
  "Mestarien mestari": '<speak><prosody rate="60%"><w role="amazon:NN">Mestarien mestari</w></prosody></speak>',
  "Meteorisade": '<speak><prosody rate="60%"><w role="amazon:NN">Meteorisade</w></prosody></speak>',
  "Miina": '<speak><prosody rate="60%"><w role="amazon:NN">Miina</w></prosody></speak>',
  "Miinankylväjä": '<speak><prosody rate="60%"><w role="amazon:NN">Miinankylväjä</w></prosody></speak>',
  "Minä": '<speak><prosody rate="60%"><w role="amazon:NN">Minä</w></prosody></speak>',
  "Mokke": '<speak><prosody rate="60%"><w role="amazon:NN">Mokke</w></prosody></speak>',
  "Molari": '<speak><prosody rate="60%"><w role="amazon:NN">Molari</w></prosody></speak>',
  "Möykky": '<speak><prosody rate="60%"><w role="amazon:NN">Möykky</w></prosody></speak>',
  "Mulkkio": '<speak><prosody rate="60%"><w role="amazon:NN">Mulkkio</w></prosody></speak>',
  "Munkki": '<speak><prosody rate="60%"><w role="amazon:NN">Munkki</w></prosody></speak>',
  "Muodonmuutosmestari": '<speak><prosody rate="60%"><w role="amazon:NN">Muodonmuutosmestari</w></prosody></speak>',
  "Murkku": '<speak><prosody rate="60%"><w role="amazon:NN">Murkku</w></prosody></speak>',
  "Myrkkyhiisi": '<speak><prosody rate="60%"><w role="amazon:NN">Myrkkyhiisi</w></prosody></speak>',
  "Myrkkynääpikkä": '<speak><prosody rate="60%"><w role="amazon:NN">Myrkkynääpikkä</w></prosody></speak>',
  "Nahkiainen": '<speak><prosody rate="60%"><w role="amazon:NN">Nahkiainen</w></prosody></speak>',
  "Nelikoipi": '<speak><prosody rate="60%"><w role="amazon:NN">Nelikoipi</w></prosody></speak>',
  "Noita": '<speak><prosody rate="60%"><w role="amazon:NN">Noita</w></prosody></speak>',
  "Nolla": '<speak><prosody rate="60%"><w role="amazon:NN">Nolla</w></prosody></speak>',
  "Nuijamalikka": '<speak><prosody rate="60%"><w role="amazon:NN">Nuijamalikka</w></prosody></speak>',
  "Olematon": '<speak><prosody rate="60%"><w role="amazon:NN">Olematon</w></prosody></speak>',
  "Paha Silmä": '<speak><prosody rate="60%"><w role="amazon:NN">Paha Silmä</w></prosody></speak>',
  "Pahan muisto": '<speak><prosody rate="60%"><w role="amazon:NN">Pahan muisto</w></prosody></speak>',
  "Pakkasukko": '<speak><prosody rate="60%"><w role="amazon:NN">Pakkasukko</w></prosody></speak>',
  "Palauttajamestari": '<speak><prosody rate="60%"><w role="amazon:NN">Palauttajamestari</w></prosody></speak>',
  "Parantajahiisi": '<speak><prosody rate="60%"><w role="amazon:NN">Parantajahiisi</w></prosody></speak>',
  "Pata": '<speak><prosody rate="60%"><w role="amazon:NN">Pata</w></prosody></speak>',
  "Patsas": '<speak><prosody rate="60%"><w role="amazon:NN">Patsas</w></prosody></speak>',
  "Peitsivartija": '<speak><prosody rate="60%"><w role="amazon:NN">Peitsivartija</w></prosody></speak>',
  "Pienkätyri": '<speak><prosody rate="60%"><w role="amazon:NN">Pienkätyri</w></prosody></speak>',
  "Pikkuhämähäkki": '<speak><prosody rate="60%"><w role="amazon:NN">Pikkuhämähäkki</w></prosody></speak>',
  "Pikkumato": '<speak><prosody rate="60%"><w role="amazon:NN">Pikkumato</w></prosody></speak>',
  "Pikkutulikärpänen": '<speak><prosody rate="60%"><w role="amazon:NN">Pikkutulikärpänen</w></prosody></speak>',
  "Pikkuturso": '<speak><prosody rate="60%"><w role="amazon:NN">Pikkuturso</w></prosody></speak>',
  "Pimeä Aurinko": '<speak><prosody rate="60%"><w role="amazon:NN">Pimeä Aurinko</w></prosody></speak>',
  "Pimeys": '<speak><prosody rate="60%"><w role="amazon:NN">Pimeys</w></prosody></speak>',
  "Plasmakukka": '<speak><prosody rate="60%"><w role="amazon:NN">Plasmakukka</w></prosody></speak>',
  "Poro": '<speak><prosody rate="60%"><w role="amazon:NN">Poro</w></prosody></speak>',
  "Puska": '<speak><prosody rate="60%"><w role="amazon:NN">Puska</w></prosody></speak>',
  "Pysäyttäjä": '<speak><prosody rate="60%"><w role="amazon:NN">Pysäyttäjä</w></prosody></speak>',
  "Raukka": '<speak><prosody rate="60%"><w role="amazon:NN">Raukka</w></prosody></speak>',
  "Rautalukki": '<speak><prosody rate="60%"><w role="amazon:NN">Rautalukki</w></prosody></speak>',
  "Rihmasto": '<speak><prosody rate="60%"><w role="amazon:NN">Rihmasto</w></prosody></speak>',
  "Riimusauva": '<speak><prosody rate="60%"><w role="amazon:NN">Riimusauva</w></prosody></speak>',
  "Robottikyttä": '<speak><prosody rate="60%"><w role="amazon:NN">Robottikyttä</w></prosody></speak>',
  "Rotta": '<speak><prosody rate="60%"><w role="amazon:NN">Rotta</w></prosody></speak>',
  "Ruttorotta": '<speak><prosody rate="60%"><w role="amazon:NN">Ruttorotta</w></prosody></speak>',
  "Ruusu": '<speak><prosody rate="60%"><w role="amazon:NN">Ruusu</w></prosody></speak>',
  "Rynkkyhiisi": '<speak><prosody rate="60%"><w role="amazon:NN">Rynkkyhiisi</w></prosody></speak>',
  "Sädekivi": '<speak><prosody rate="60%"><w role="amazon:NN">Sädekivi</w></prosody></speak>',
  "Sähikäinen": '<speak><prosody rate="60%"><w role="amazon:NN">Sähikäinen</w></prosody></speak>',
  "Sähikäismenninkäinen": '<speak><prosody rate="60%"><w role="amazon:NN">Sähikäismenninkäinen</w></prosody></speak>',
  "Sähkiö": '<speak><prosody rate="60%"><w role="amazon:NN">Sähkiö</w></prosody></speak>',
  "Salamurhaajarobotti": '<speak><prosody rate="60%"><w role="amazon:NN">Salamurhaajarobotti</w></prosody></speak>',
  "Sampo": '<speak><prosody rate="60%"><w role="amazon:NN">Sampo</w></prosody></speak>',
  "Sappitatti": '<speak><prosody rate="60%"><w role="amazon:NN">Sappitatti</w></prosody></speak>',
  "Sätkymestari": '<speak><prosody rate="60%"><w role="amazon:NN">Sätkymestari</w></prosody></speak>',
  "Sauvan Ydin": '<speak><prosody rate="60%"><w role="amazon:NN">Sauvan Ydin</w></prosody></speak>',
  "Sauvojen tuntija": '<speak><prosody rate="60%"><w role="amazon:NN">Sauvojen tuntija</w></prosody></speak>',
  "Seula": '<speak><prosody rate="60%"><w role="amazon:NN">Seula</w></prosody></speak>',
  "Siirtäjämestari": '<speak><prosody rate="60%"><w role="amazon:NN">Siirtäjämestari</w></prosody></speak>',
  "Sima": '<speak><prosody rate="60%"><w role="amazon:NN">Sima</w></prosody></speak>',
  "Skorpioni": '<speak><prosody rate="60%"><w role="amazon:NN">Skorpioni</w></prosody></speak>',
  "Skoude": '<speak><prosody rate="60%"><w role="amazon:NN">Skoude</w></prosody></speak>',
  "Snipuhiisi": '<speak><prosody rate="60%"><w role="amazon:NN">Snipuhiisi</w></prosody></speak>',
  "Sokaisunmestari": '<speak><prosody rate="60%"><w role="amazon:NN">Sokaisunmestari</w></prosody></speak>',
  "Spiraalikalma": '<speak><prosody rate="60%"><w role="amazon:NN">Spiraalikalma</w></prosody></speak>',
  "Stendari": '<speak><prosody rate="60%"><w role="amazon:NN">Stendari</w></prosody></speak>',
  "Stevari": '<speak><prosody rate="60%"><w role="amazon:NN">Stevari</w></prosody></speak>',
  "Suhiseva lammas": '<speak><prosody rate="60%"><w role="amazon:NN">Suhiseva lammas</w></prosody></speak>',
  "Suomuhauki": '<speak><prosody rate="60%"><w role="amazon:NN">Suomuhauki</w></prosody></speak>',
  "Supernova": '<speak><prosody rate="60%"><w role="amazon:NN">Supernova</w></prosody></speak>',
  "Susi": '<speak><prosody rate="60%"><w role="amazon:NN">Susi</w></prosody></speak>',
  "Suur-Ukko": '<speak><prosody rate="60%"><w role="amazon:NN">Suur-Ukko</w></prosody></speak>',
  "Suureväkäs": '<speak><prosody rate="60%"><w role="amazon:NN">Suureväkäs</w></prosody></speak>',
  "Suurlepakko": '<speak><prosody rate="60%"><w role="amazon:NN">Suurlepakko</w></prosody></speak>',
  "Suurstendari": '<speak><prosody rate="60%"><w role="amazon:NN">Suurstendari</w></prosody></speak>',
  "Suurtulikärpänen": '<speak><prosody rate="60%"><w role="amazon:NN">Suurtulikärpänen</w></prosody></speak>',
  "Sylkyri": '<speak><prosody rate="60%"><w role="amazon:NN">Sylkyri</w></prosody></speak>',
  "Syväolento": '<speak><prosody rate="60%"><w role="amazon:NN">Syväolento</w></prosody></speak>',
  "Tähdenpoikanen": '<speak><prosody rate="60%"><w role="amazon:NN">Tähdenpoikanen</w></prosody></speak>',
  "Taikasauva": '<speak><prosody rate="60%"><w role="amazon:NN">Taikasauva</w></prosody></speak>',
  "Taivaankatse": '<speak><prosody rate="60%"><w role="amazon:NN">Taivaankatse</w></prosody></speak>',
  "Taivaskristalli": '<speak><prosody rate="60%"><w role="amazon:NN">Taivaskristalli</w></prosody></speak>',
  "Tannerkivi": '<speak><prosody rate="60%"><w role="amazon:NN">Tannerkivi</w></prosody></speak>',
  "Tappurahiisi": '<speak><prosody rate="60%"><w role="amazon:NN">Tappurahiisi</w></prosody></speak>',
  "Tappurahiisiläinen": '<speak><prosody rate="60%"><w role="amazon:NN">Tappurahiisiläinen</w></prosody></speak>',
  "Tarkkailija": '<speak><prosody rate="60%"><w role="amazon:NN">Tarkkailija</w></prosody></speak>',
  "Teloittaja": '<speak><prosody rate="60%"><w role="amazon:NN">Teloittaja</w></prosody></speak>',
  "Toimari": '<speak><prosody rate="60%"><w role="amazon:NN">Toimari</w></prosody></speak>',
  "Torjuntalaite": '<speak><prosody rate="60%"><w role="amazon:NN">Torjuntalaite</w></prosody></speak>',
  "Toukka": '<speak><prosody rate="60%"><w role="amazon:NN">Toukka</w></prosody></speak>',
  "Toveri": '<speak><prosody rate="60%"><w role="amazon:NN">Toveri</w></prosody></speak>',
  "Toveri lohkare": '<speak><prosody rate="60%"><w role="amazon:NN">Toveri lohkare</w></prosody></speak>',
  "Tulihiisi": '<speak><prosody rate="60%"><w role="amazon:NN">Tulihiisi</w></prosody></speak>',
  "Tuonelankone": '<speak><prosody rate="60%"><w role="amazon:NN">Tuonelankone</w></prosody></speak>',
  "Turso": '<speak><prosody rate="60%"><w role="amazon:NN">Turso</w></prosody></speak>',
  "Turvalennokki": '<speak><prosody rate="60%"><w role="amazon:NN">Turvalennokki</w></prosody></speak>',
  "Turvattomuusmestari": '<speak><prosody rate="60%"><w role="amazon:NN">Turvattomuusmestari</w></prosody></speak>',
  "Turvonnu velho": '<speak><prosody rate="60%"><w role="amazon:NN">Turvonnu velho</w></prosody></speak>',
  "Ukko": '<speak><prosody rate="60%"><w role="amazon:NN">Ukko</w></prosody></speak>',
  "Ukkoshyypiö": '<speak><prosody rate="60%"><w role="amazon:NN">Ukkoshyypiö</w></prosody></speak>',
  "Ukkoskivi": '<speak><prosody rate="60%"><w role="amazon:NN">Ukkoskivi</w></prosody></speak>',
  "Ukkoskoira": '<speak><prosody rate="60%"><w role="amazon:NN">Ukkoskoira</w></prosody></speak>',
  "Unohdettu": '<speak><prosody rate="60%"><w role="amazon:NN">Unohdettu</w></prosody></speak>',
  "Uusi Aurinko": '<speak><prosody rate="60%"><w role="amazon:NN">Uusi Aurinko</w></prosody></speak>',
  "Vaihdosmestari": '<speak><prosody rate="60%"><w role="amazon:NN">Vaihdosmestari</w></prosody></speak>',
  "Vakoilija": '<speak><prosody rate="60%"><w role="amazon:NN">Vakoilija</w></prosody></speak>',
  "Valaistunut alkemisti": '<speak><prosody rate="60%"><w role="amazon:NN">Valaistunut alkemisti</w></prosody></speak>',
  "Valo": '<speak><prosody rate="60%"><w role="amazon:NN">Valo</w></prosody></speak>',
  "Valtikka": '<speak><prosody rate="60%"><w role="amazon:NN">Valtikka</w></prosody></speak>',
  "Varjokupla": '<speak><prosody rate="60%"><w role="amazon:NN">Varjokupla</w></prosody></speak>',
  "Varpuluuta": '<speak><prosody rate="60%"><w role="amazon:NN">Varpuluuta</w></prosody></speak>',
  "Vasta": '<speak><prosody rate="60%"><w role="amazon:NN">Vasta</w></prosody></speak>',
  "Verikristalli": '<speak><prosody rate="60%"><w role="amazon:NN">Verikristalli</w></prosody></speak>',
  "Veska": '<speak><prosody rate="60%"><w role="amazon:NN">Veska</w></prosody></speak>',
  "Vihta": '<speak><prosody rate="60%"><w role="amazon:NN">Vihta</w></prosody></speak>',
  "Vuoksikivi": '<speak><prosody rate="60%"><w role="amazon:NN">Vuoksikivi</w></prosody></speak>',
  "Ylialkemisti": '<speak><prosody rate="60%"><w role="amazon:NN">Ylialkemisti</w></prosody></speak>'
}


session = Session(region_name="us-east-1",aws_access_key_id="",aws_secret_access_key="")
polly = session.client("polly")

for name, querytext in entries.items():
  print(f"Synthesizing {name}")

  response = {}
  success = False
  while not success:
    try:
      response = polly.synthesize_speech(
        Engine="neural",
        LanguageCode="fi-FI",
        OutputFormat="mp3",
        SampleRate="24000",
        Text=querytext,
        TextType="ssml",
        VoiceId="Suvi"
      )
      success = True
    except (BotoCoreError, ClientError) as error:
      print(error)
      time.sleep(1)

  if "AudioStream" not in response:
    print(f"Response failed to include audiostream for {name}\n")
    continue

  with closing(response["AudioStream"]) as stream:
    output = f"results/{name}.mp3"
    try:
      with open(output, "wb") as file:
        file.write(stream.read())
    except IOError as error:
      print(error)

  time.sleep(0.5)
