import speech_recognition as sr
from pydub import AudioSegment
import phonemizer
import pyphen
import time

entries = [
  "results/Äitilimanuljaska.mp3",
  "results/Äitinuljaska.mp3",
  "results/Alkemisti.mp3",
  "results/Alkemistin Varjo.mp3",
  "results/Amppari.mp3",
  "results/Ankka.mp3",
  "results/Arpaluu.mp3",
  "results/Auringonmuna.mp3",
  "results/Auringonsiemen.mp3",
  "results/Aurinkokivi.mp3",
  "results/Eldari.mp3",
  "results/Elvytyskristalli.mp3",
  "results/Epäalkemisti.mp3",
  "results/Eväkäs.mp3",
  "results/Haamu.mp3",
  "results/Haamukivi.mp3",
  "results/Haavoittajamestari.mp3",
  "results/Hahmonvaihtaja.mp3",
  "results/Häive.mp3",
  "results/Häivehiisi.mp3",
  "results/Hämähäkki.mp3",
  "results/Hämis.mp3",
  "results/Happonuljaska.mp3",
  "results/Haulikkohiisi.mp3",
  "results/Heikko äitinuljaska.mp3",
  "results/Heikko happonuljaska.mp3",
  "results/Heikko haulikkohiisi.mp3",
  "results/Heikko limanuljaska.mp3",
  "results/Heikkohurtta.mp3",
  "results/Heinäsirkka.mp3",
  "results/Helvetin sylkijä.mp3",
  "results/Helvetinkatse.mp3",
  "results/Helvetinmato.mp3",
  "results/Hernekeittopurkki.mp3",
  "results/Hiidenkivi.mp3",
  "results/Hohtava hyypiö.mp3",
  "results/Hohtonaamio.mp3",
  "results/Houre.mp3",
  "results/Huhtasieni.mp3",
  "results/Huilu.mp3",
  "results/Hurtta.mp3",
  "results/Hyypiö.mp3",
  "results/Isohiisi.mp3",
  "results/IT-Tankki.mp3",
  "results/Itiösieni.mp3",
  "results/Jäähdytyslaite.mp3",
  "results/Jäätiö.mp3",
  "results/Jalkamatkatavara.mp3",
  "results/Jättikonna.mp3",
  "results/Jättilaser-lennokki.mp3",
  "results/Jättimato.mp3",
  "results/Jouluhiisi.mp3",
  "results/Juhannussima.mp3",
  "results/Kadotettu alkemisti.mp3",
  "results/Kakkakikkare.mp3",
  "results/Kaljapullo.mp3",
  "results/Kallokärpänen.mp3",
  "results/Kallorotta.mp3",
  "results/Kalmamato.mp3",
  "results/Kammi.mp3",
  "results/Kammolukki.mp3",
  "results/Kantele.mp3",
  "results/Kärpässieni.mp3",
  "results/Kasvoton Hämähäkki.mp3",
  "results/Kasvoton Lukki.mp3",
  "results/Kauhuhirviö.mp3",
  "results/Kiekurakeppi.mp3",
  "results/Kilpihiisi.mp3",
  "results/Kirottu kristalli.mp3",
  "results/Kiuaskivi.mp3",
  "results/Kiukkukalma.mp3",
  "results/Kiukkumöykky.mp3",
  "results/KK-Tankki.mp3",
  "results/Kohdennusmestari.mp3",
  "results/Kokkihiisi.mp3",
  "results/Kolmisilmä.mp3",
  "results/Kolmisilmän apuri.mp3",
  "results/Kolmisilmän kätyri.mp3",
  "results/Kolmisilmän koipi.mp3",
  "results/Kolmisilmän silmä.mp3",
  "results/Konna.mp3",
  "results/Korjauslennokki.mp3",
  "results/Kranuhiisi.mp3",
  "results/Kuihduttajamestari.mp3",
  "results/Kummitus.mp3",
  "results/Kuu.mp3",
  "results/Kuulokivi.mp3",
  "results/Kyrmyniska.mp3",
  "results/Laahustussieni.mp3",
  "results/Lammas.mp3",
  "results/Laser-tankki.mp3",
  "results/Laserkanuuna.mp3",
  "results/Lennokki.mp3",
  "results/Lentolammas.mp3",
  "results/Lepakko.mp3",
  "results/Liekkari.mp3",
  "results/Liekkiö.mp3",
  "results/Liimahiisi.mp3",
  "results/Limanuljaska.mp3",
  "results/Limatoukka.mp3",
  "results/Lohkare.mp3",
  "results/Lukki.mp3",
  "results/Lukki lair.mp3",
  "results/Lukki Minion.mp3",
  "results/Maadoittajamestari.mp3",
  "results/Maamiina.mp3",
  "results/Mämmi.mp3",
  "results/Märkiäinen.mp3",
  "results/Marraskone.mp3",
  "results/Mätänevä kroppa.mp3",
  "results/Mätänevä pää.mp3",
  "results/Mätänevä ruumis.mp3",
  "results/Matkija.mp3",
  "results/Mato.mp3",
  "results/Matosade.mp3",
  "results/Mestarien mestari.mp3",
  "results/Meteorisade.mp3",
  "results/Miina.mp3",
  "results/Miinankylväjä.mp3",
  "results/Minä.mp3",
  "results/Mokke.mp3",
  "results/Molari.mp3",
  "results/Möykky.mp3",
  "results/Mulkkio.mp3",
  "results/Munkki.mp3",
  "results/Muodonmuutosmestari.mp3",
  "results/Murkku.mp3",
  "results/Myrkkyhiisi.mp3",
  "results/Myrkkynääpikkä.mp3",
  "results/Nahkiainen.mp3",
  "results/Nelikoipi.mp3",
  "results/Noita.mp3",
  "results/Nolla.mp3",
  "results/Nuijamalikka.mp3",
  "results/Olematon.mp3",
  "results/Paha Silmä.mp3",
  "results/Pahan muisto.mp3",
  "results/Pakkasukko.mp3",
  "results/Palauttajamestari.mp3",
  "results/Parantajahiisi.mp3",
  "results/Pata.mp3",
  "results/Patsas.mp3",
  "results/Peitsivartija.mp3",
  "results/Pienkätyri.mp3",
  "results/Pikkuhämähäkki.mp3",
  "results/Pikkumato.mp3",
  "results/Pikkutulikärpänen.mp3",
  "results/Pikkuturso.mp3",
  "results/Pimeä Aurinko.mp3",
  "results/Pimeys.mp3",
  "results/Plasmakukka.mp3",
  "results/Poro.mp3",
  "results/Puska.mp3",
  "results/Pysäyttäjä.mp3",
  "results/Raukka.mp3",
  "results/Rautalukki.mp3",
  "results/Rihmasto.mp3",
  "results/Riimusauva.mp3",
  "results/Robottikyttä.mp3",
  "results/Rotta.mp3",
  "results/Ruttorotta.mp3",
  "results/Ruusu.mp3",
  "results/Rynkkyhiisi.mp3",
  "results/Sädekivi.mp3",
  "results/Sähikäinen.mp3",
  "results/Sähikäismenninkäinen.mp3",
  "results/Sähkiö.mp3",
  "results/Salamurhaajarobotti.mp3",
  "results/Sampo.mp3",
  "results/Sappitatti.mp3",
  "results/Sätkymestari.mp3",
  "results/Sauvan Ydin.mp3",
  "results/Sauvojen tuntija.mp3",
  "results/Seula.mp3",
  "results/Siirtäjämestari.mp3",
  "results/Sima.mp3",
  "results/Skorpioni.mp3",
  "results/Skoude.mp3",
  "results/Snipuhiisi.mp3",
  "results/Sokaisunmestari.mp3",
  "results/Spiraalikalma.mp3",
  "results/Stendari.mp3",
  "results/Stevari.mp3",
  "results/Suhiseva lammas.mp3",
  "results/Suomuhauki.mp3",
  "results/Supernova.mp3",
  "results/Susi.mp3",
  "results/Suur-Ukko.mp3",
  "results/Suureväkäs.mp3",
  "results/Suurlepakko.mp3",
  "results/Suurstendari.mp3",
  "results/Suurtulikärpänen.mp3",
  "results/Sylkyri.mp3",
  "results/Syväolento.mp3",
  "results/Tähdenpoikanen.mp3",
  "results/Taikasauva.mp3",
  "results/Taivaankatse.mp3",
  "results/Taivaskristalli.mp3",
  "results/Tannerkivi.mp3",
  "results/Tappurahiisi.mp3",
  "results/Tappurahiisiläinen.mp3",
  "results/Tarkkailija.mp3",
  "results/Teloittaja.mp3",
  "results/Toimari.mp3",
  "results/Torjuntalaite.mp3",
  "results/Toukka.mp3",
  "results/Toveri.mp3",
  "results/Toveri lohkare.mp3",
  "results/Tulihiisi.mp3",
  "results/Tuonelankone.mp3",
  "results/Turso.mp3",
  "results/Turvalennokki.mp3",
  "results/Turvattomuusmestari.mp3",
  "results/Turvonnu velho.mp3",
  "results/Ukko.mp3",
  "results/Ukkoshyypiö.mp3",
  "results/Ukkoskivi.mp3",
  "results/Ukkoskoira.mp3",
  "results/Unohdettu.mp3",
  "results/Uusi Aurinko.mp3",
  "results/Vaihdosmestari.mp3",
  "results/Vakoilija.mp3",
  "results/Valaistunut alkemisti.mp3",
  "results/Valo.mp3",
  "results/Valtikka.mp3",
  "results/Varjokupla.mp3",
  "results/Varpuluuta.mp3",
  "results/Vasta.mp3",
  "results/Verikristalli.mp3",
  "results/Veska.mp3",
  "results/Vihta.mp3",
  "results/Vuoksikivi.mp3",
  "results/Ylialkemisti.mp3",
]

for item in entries:
  time.sleep(1)
  lang = "en"
  phoneme_system = "ipa"
  syllable_dict = pyphen.Pyphen(lang="sv")

  # Load the audio file
  audio_file = AudioSegment.from_mp3(item)

  # Convert the audio to a format that can be used by the speech recognition library
  audio_wav = audio_file.export(format="wav")

  # Transcribe the audio to text
  r = sr.Recognizer()
  with sr.AudioFile(audio_wav) as source:
      audio_data = r.record(source)

  text = r.recognize_google(audio_data, language="fi")
  print(text)

  # Transcribe the foreign word to its phonetic representation
  phonemes = phonemizer.phonemize(text=text, language="sv", backend="espeak", 
                                  language_switch="remove-flags", strip=True, 
                                  preserve_punctuation=True, with_stress=False, 
                                  njobs=1)

  # Syllabify the phonetic representation
  syllables = syllable_dict.inserted(phonemes)

  # Print the syllables
  print(syllables)
